package catgpt;

import java.util.Scanner;

/**
 * Handles all console input and output for CatGPT.
 */
public class Ui {
    private static final String BANNER = "  ____      _    ____ ____ _____ \n"
            + " / ___|__ _| |_ / ___|  _ \\_   _|\n"
            + "| |   / _` | __| |  _| |_) || |  \n"
            + "| |__| (_| | |_| |_| |  __/ | |  \n"
            + " \\____\\__,_|\\__|\\____|_|    |_|  \n";

    private final Scanner scanner;

    /**
     * Creates a console UI that reads from standard input.
     */
    public Ui() {
        scanner = new Scanner(System.in);
    }

    /**
     * Displays CatGPT's banner and greeting.
     */
    public void showWelcome() {
        System.out.println(BANNER);
        System.out.println(getWelcomeMessage());
    }

    /**
     * Reads the next command, or returns {@code null} when input ends.
     *
     * @return Next command, or {@code null} at end of input.
     */
    public String readCommand() {
        return scanner.hasNextLine() ? scanner.nextLine() : null;
    }

    /**
     * Displays CatGPT's farewell message.
     */
    public void showGoodbye() {
        System.out.println(getGoodbyeMessage());
    }

    /**
     * Displays a response generated by CatGPT.
     *
     * @param response Response to display.
     */
    public void showResponse(String response) {
        System.out.println(response);
    }

    /**
     * Displays a user-friendly error message.
     *
     * @param message Explanation of the error.
     */
    public void showError(String message) {
        System.out.println(formatError(message));
    }

    /**
     * Returns CatGPT's greeting without its console-only banner.
     *
     * @return Greeting for the user.
     */
    public String getWelcomeMessage() {
        return "Hello! I'm CatGPT.\nWhat can I do for you?";
    }

    /**
     * Returns CatGPT's farewell message.
     *
     * @return Farewell for the user.
     */
    public String getGoodbyeMessage() {
        return "Bye. Hope to see you again soon!";
    }

    /**
     * Formats a user-friendly error message.
     *
     * @param message Explanation of the error.
     * @return Formatted error response.
     */
    public String formatError(String message) {
        return "OOPS!!! " + message;
    }

    /**
     * Formats all tasks with one-based numbering.
     *
     * @param tasks Tasks to display.
     * @return Formatted task list.
     */
    public String formatTaskList(TaskList tasks) {
        StringBuilder response = new StringBuilder("Here are the tasks in your list:");
        int taskNumber = 1;
        for (Task task : tasks) {
            response.append(System.lineSeparator()).append(taskNumber).append('.').append(task);
            taskNumber++;
        }
        return response.toString();
    }

    /**
     * Formats tasks that match a find command with one-based numbering.
     *
     * @param tasks Matching tasks to display.
     * @return Formatted matching tasks.
     */
    public String formatMatchingTasks(TaskList tasks) {
        StringBuilder response = new StringBuilder("Here are the matching tasks in your list:");
        int taskNumber = 1;
        for (Task task : tasks) {
            response.append(System.lineSeparator()).append(taskNumber).append('.').append(task);
            taskNumber++;
        }
        return response.toString();
    }

    /**
     * Formats confirmation that a task was added.
     *
     * @param task Added task.
     * @param taskCount Resulting number of tasks.
     * @return Formatted confirmation.
     */
    public String formatTaskAdded(Task task, int taskCount) {
        return "Got it. I've added this task:\n" + task + "\n" + formatTaskCount(taskCount);
    }

    /**
     * Formats confirmation that a task was deleted.
     *
     * @param task Deleted task.
     * @param taskCount Resulting number of tasks.
     * @return Formatted confirmation.
     */
    public String formatTaskDeleted(Task task, int taskCount) {
        return "Noted. I've removed this task:\n" + task + "\n" + formatTaskCount(taskCount);
    }

    /**
     * Formats confirmation of a task status change.
     *
     * @param task Updated task.
     * @param isDone Whether the task was marked completed.
     * @return Formatted confirmation.
     */
    public String formatTaskStatusChanged(Task task, boolean isDone) {
        String message = isDone
                ? "Nice! I've marked this task as done:"
                : "OK! I've marked this task as not done yet:";
        return message + "\n" + task;
    }

    private String formatTaskCount(int taskCount) {
        String taskWord = taskCount == 1 ? "task" : "tasks";
        return "Now you have " + taskCount + " " + taskWord + " in the list.";
    }
}
